#!/bin/bash

# Define the target branches
target_branches=("dev" "UAT" "PRE-PROD" "main")

# Define the branch labels
branch_labels=("Dev" "UAT" "PRE-PROD" "Production")

# Get the current branch name
current_branch=$(git rev-parse --abbrev-ref HEAD)

pr_links=()

# Function to create a pull request
create_pull_request() {
  local branch=$1
  local title=$2
  local label=$3
  local response=$(gh pr create --base "$branch" --head "$current_branch" --title "$title" --body="" --label "$label" 2>&1)
  echo "$label: $response"
}

# Prompt for the pull request title
read -p "Enter the pull request title: " pr_title

# Iterate over target branches
for ((i=0; i<${#target_branches[@]}; i++)); do
  branch=${target_branches[$i]}
  label=${branch_labels[$i]}
  # Create pull request with label
  create_pull_request "$branch" "$pr_title" "$label"
done
